### ISSUE TITLE
Operation not permitted: When attempting to install.

### ISSUE THREAD

**Issue by sciku1** [samiare/whitewater-encoder#5]
With or without sudo, I am unable to install the encoder, here is the stack trace:

```
Requirement already satisfied (use --upgrade to upgrade): whitewater in /Library/Python/2.7/site-packages/whitewater-1.0.1-py2.7.egg
Collecting docopt>=0.6.2 (from whitewater)
  Downloading docopt-0.6.2.tar.gz
Collecting imageio>=1.4 (from whitewater)
  Downloading imageio-1.5-cp26.cp27.cp33.cp34.cp35-none-macosx_10_5_x86_64.macosx_10_6_intel.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 255kB/s
Collecting numpy>=1.10.2 (from whitewater)
  Downloading numpy-1.11.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 336kB/s
Collecting Pillow>=3.0.0 (from whitewater)
  Downloading Pillow-3.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.2MB)
    100% |████████████████████████████████| 3.2MB 409kB/s
Installing collected packages: docopt, imageio, numpy, Pillow
  Running setup.py install for docopt ... done
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-ecyc3D-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
```

I think it has something to do with the deprecated command? Anyone have a better guess? I'm a bit rusty on my Python.
Some additional information:
I'm on a mac running OS X 10.11.5 (15F34). 
Python Version: Python 2.7.10
I'll provide more if needed.

EDIT: 
I also tried installing it in a CentOS6.7 machine and I got the same error.

**Comment by wladino** [comment]
I tried using this command " sudo pip install whitewater --ingnore-installed six " and it did work

**Comment by grumpyoldman-io** [comment]
@wladino that just outputs "no such option: --ingnore-installed".

@sciku1 I got one step further by installing the dependencies manually but still the install process freezes and whitewater will not run on OSX, I think it has something to do with the native 2.7 python vs the one installed with homebrew. I hope someone can do a complete install guide for osx.

**Comment by Hursofid** [comment]
@grumpyoldman-io try with option --ignore-installed

**Comment by sciku1** [comment]
Thanks for the help! We ended up not using this solution, but I tried installing it with --ignore-installed and it worked! I hope this is useful if someone!
