### ISSUE TITLE
It seems it broke on macos Sierra

### ISSUE THREAD

**Issue by zomars** [samiare/whitewater-encoder#6]
I'm getting this  error when trying to encode any video.

```
zommy:~ zomars$ whitewater /private/tmp/video-example-small.mp4 
START /private/tmp/video-example-small.mp4                       
Traceback (most recent call last):                                              
  File "/usr/local/bin/whitewater", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/whitewater/cli.py", line 113, in main
    encoder.encode()
  File "/usr/local/lib/python2.7/site-packages/whitewater/whitewater.py", line 79, in encode
    for frame in enumerate(self.video):
  File "/usr/local/lib/python2.7/site-packages/imageio/core/format.py", line 375, in iter_data
    im, meta = self._get_data(i)
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 326, in _get_data
    result = self._read_frame()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 526, in _read_frame
    s = self._read_frame_data()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 512, in _read_frame_data
    raise RuntimeError(fmt % (err1, err2))
RuntimeError: Could not read frame:

=== stderr ===
ffmpeg version 3.1.4 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-libfdk-aac --disable-lzma --enable-nonfree --enable-vda
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/private/tmp/video-example-small.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2016-10-03 23:09:10
    encoder         : HandBrake 0.10.5 2016021100
  Duration: 00:00:09.58, start: 0.000000, bitrate: 1935 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 960x540 [SAR 1:1 DAR 16:9], 1857 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2016-10-03 23:09:10
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 83 kb/s (default)
    Metadata:
      creation_time   : 2016-10-03 23:09:10
      handler_name    : Stereo
[image2pipe @ 0x7fc43e010a00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.41.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 960x540 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2016-10-03 23:09:10
      handler_name    : VideoHandler
      encoder         : Lavc57.48.101 rawvideo
Stream mapping:
... showing only last few lines ...
frame=  195 fps=0.4 q=-0.0 size=  296156kB time=00:00:08.13 bitrate=298300.1kbits/s speed=0.0148x    
frame=  196 fps=0.4 q=-0.0 size=  297675kB time=00:00:08.17 bitrate=298300.1kbits/s speed=0.0148x    
frame=  197 fps=0.4 q=-0.0 size=  299194kB time=00:00:08.21 bitrate=298300.1kbits/s speed=0.0148x    
frame=  198 fps=0.4 q=-0.0 size=  300712kB time=00:00:08.25 bitrate=298300.1kbits/s speed=0.0148x    
frame=  199 fps=0.4 q=-0.0 size=  302231kB time=00:00:08.29 bitrate=298300.1kbits/s speed=0.0148x    
frame=  200 fps=0.4 q=-0.0 size=  303750kB time=00:00:08.34 bitrate=298300.1kbits/s speed=0.0148x    
frame=  201 fps=0.4 q=-0.0 size=  305269kB time=00:00:08.38 bitrate=298300.1kbits/s speed=0.0148x    
frame=  202 fps=0.4 q=-0.0 size=  306788kB time=00:00:08.42 bitrate=298300.1kbits/s speed=0.0149x    
frame=  203 fps=0.4 q=-0.0 size=  308306kB time=00:00:08.46 bitrate=298300.1kbits/s speed=0.0149x    
frame=  204 fps=0.4 q=-0.0 size=  309825kB time=00:00:08.50 bitrate=298300.1kbits/s speed=0.0149x    
frame=  205 fps=0.4 q=-0.0 size=  311344kB time=00:00:08.55 bitrate=298300.1kbits/s speed=0.0149x    
frame=  206 fps=0.4 q=-0.0 size=  312862kB time=00:00:08.59 bitrate=298300.1kbits/s speed=0.0149x    
frame=  207 fps=0.4 q=-0.0 size=  314381kB time=00:00:08.63 bitrate=298300.1kbits/s speed=0.0148x    
frame=  208 fps=0.4 q=-0.0 size=  315900kB time=00:00:08.67 bitrate=298300.1kbits/s speed=0.0148x    
frame=  209 fps=0.4 q=-0.0 size=  317419kB time=00:00:08.71 bitrate=298300.1kbits/s speed=0.0146x    
frame=  210 fps=0.3 q=-0.0 size=  318938kB time=00:00:08.75 bitrate=298300.1kbits/s speed=0.0146x    
frame=  211 fps=0.3 q=-0.0 size=  320456kB time=00:00:08.80 bitrate=298300.1kbits/s speed=0.0145x    
frame=  212 fps=0.3 q=-0.0 size=  321975kB time=00:00:08.84 bitrate=298300.1kbits/s speed=0.0145x    
frame=  213 fps=0.3 q=-0.0 size=  323494kB time=00:00:08.88 bitrate=298300.1kbits/s speed=0.0145x    
frame=  214 fps=0.3 q=-0.0 size=  325012kB time=00:00:08.92 bitrate=298300.1kbits/s speed=0.0145x    
frame=  215 fps=0.3 q=-0.0 size=  326531kB time=00:00:08.96 bitrate=298300.1kbits/s speed=0.0145x    
frame=  216 fps=0.3 q=-0.0 size=  328050kB time=00:00:09.00 bitrate=298300.1kbits/s speed=0.0143x    
frame=  217 fps=0.3 q=-0.0 size=  329569kB time=00:00:09.05 bitrate=298300.1kbits/s speed=0.0143x    
frame=  218 fps=0.3 q=-0.0 size=  331088kB time=00:00:09.09 bitrate=298300.1kbits/s speed=0.0143x    
frame=  219 fps=0.3 q=-0.0 size=  332606kB time=00:00:09.13 bitrate=298300.1kbits/s speed=0.0143x    
frame=  220 fps=0.3 q=-0.0 size=  334125kB time=00:00:09.17 bitrate=298300.1kbits/s speed=0.0143x    
frame=  221 fps=0.3 q=-0.0 size=  335644kB time=00:00:09.21 bitrate=298300.1kbits/s speed=0.0142x    
frame=  222 fps=0.3 q=-0.0 size=  337162kB time=00:00:09.25 bitrate=298300.1kbits/s speed=0.0142x    
frame=  223 fps=0.3 q=-0.0 size=  338681kB time=00:00:09.30 bitrate=298300.1kbits/s speed=0.0142x    
frame=  224 fps=0.3 q=-0.0 size=  340200kB time=00:00:09.34 bitrate=298300.1kbits/s speed=0.0142x    
frame=  225 fps=0.3 q=-0.0 size=  341719kB time=00:00:09.38 bitrate=298300.1kbits/s speed=0.0142x    
frame=  226 fps=0.3 q=-0.0 size=  343238kB time=00:00:09.42 bitrate=298300.1kbits/s speed=0.0143x    
frame=  227 fps=0.3 q=-0.0 size=  344756kB time=00:00:09.46 bitrate=298300.1kbits/s speed=0.0143x    
frame=  228 fps=0.3 q=-0.0 size=  346275kB time=00:00:09.50 bitrate=298300.1kbits/s speed=0.0143x    
frame=  228 fps=0.3 q=-0.0 size=  346275kB time=00:00:09.50 bitrate=298300.1kbits/s speed=0.0142x    
frame=  228 fps=0.3 q=-0.0 Lsize=  346275kB time=00:00:09.50 bitrate=298300.1kbits/s speed=0.0142x    
video:346275kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

**Comment by maxtherocket** [comment]
Having the same issue here:
```
Traceback (most recent call last):
  File "/usr/local/bin/whitewater", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/whitewater/cli.py", line 113, in main
    encoder.encode()
  File "/usr/local/lib/python2.7/site-packages/whitewater/whitewater.py", line 79, in encode
    for frame in enumerate(self.video):
  File "/usr/local/lib/python2.7/site-packages/imageio/core/format.py", line 375, in iter_data
    im, meta = self._get_data(i)
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 326, in _get_data
    result = self._read_frame()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 526, in _read_frame
    s = self._read_frame_data()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 512, in _read_frame_data
    raise RuntimeError(fmt % (err1, err2))
RuntimeError: Could not read frame:

=== stderr ===
ffmpeg version 3.2.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/max/projects/tameTheDragon/video/new-intro/00___Dragon Intro Main Page_Animation In.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2016-11-29T03:06:27.000000Z
  Duration: 00:00:04.07, start: 0.000000, bitrate: 7164 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 6947 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2016-11-29T03:06:27.000000Z
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2016-11-29T03:06:27.000000Z
      handler_name    : Alias Data Handler
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf57.56.100
    Stream #0:0(eng): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      creation_time   : 2016-11-29T03:06:27.000000Z
      handler_name    : Alias Data Handler
      encoder         : Lavc57.64.101 rawvideo
Stream mapping:
... showing only last few lines ...
frame=   67 fps=0.4 q=-0.0 size=  180900kB time=00:00:02.79 bitrate=530841.5kbits/s speed=0.0175x
frame=   68 fps=0.4 q=-0.0 size=  183600kB time=00:00:02.83 bitrate=530841.7kbits/s speed=0.0175x
frame=   69 fps=0.4 q=-0.0 size=  186300kB time=00:00:02.87 bitrate=530841.6kbits/s speed=0.0174x
frame=   70 fps=0.4 q=-0.0 size=  189000kB time=00:00:02.91 bitrate=530841.5kbits/s speed=0.0173x
frame=   71 fps=0.4 q=-0.0 size=  191700kB time=00:00:02.95 bitrate=530841.7kbits/s speed=0.0173x
frame=   72 fps=0.4 q=-0.0 size=  194400kB time=00:00:03.00 bitrate=530841.6kbits/s speed=0.0173x
frame=   73 fps=0.4 q=-0.0 size=  197100kB time=00:00:03.04 bitrate=530841.5kbits/s speed=0.0171x
frame=   74 fps=0.4 q=-0.0 size=  199800kB time=00:00:03.08 bitrate=530841.7kbits/s speed=0.0169x
frame=   75 fps=0.4 q=-0.0 size=  202500kB time=00:00:03.12 bitrate=530841.6kbits/s speed=0.0169x
frame=   76 fps=0.4 q=-0.0 size=  205200kB time=00:00:03.16 bitrate=530841.5kbits/s speed=0.0168x
frame=   77 fps=0.4 q=-0.0 size=  207900kB time=00:00:03.20 bitrate=530841.7kbits/s speed=0.0167x
frame=   78 fps=0.4 q=-0.0 size=  210600kB time=00:00:03.25 bitrate=530841.6kbits/s speed=0.0166x
frame=   79 fps=0.4 q=-0.0 size=  213300kB time=00:00:03.29 bitrate=530841.5kbits/s speed=0.0166x
frame=   80 fps=0.4 q=-0.0 size=  216000kB time=00:00:03.33 bitrate=530841.7kbits/s speed=0.0165x
frame=   81 fps=0.4 q=-0.0 size=  218700kB time=00:00:03.37 bitrate=530841.6kbits/s speed=0.0164x
frame=   82 fps=0.4 q=-0.0 size=  221400kB time=00:00:03.41 bitrate=530841.5kbits/s speed=0.0163x
frame=   83 fps=0.4 q=-0.0 size=  224100kB time=00:00:03.45 bitrate=530841.7kbits/s speed=0.0163x
frame=   84 fps=0.4 q=-0.0 size=  226800kB time=00:00:03.50 bitrate=530841.6kbits/s speed=0.0163x
frame=   85 fps=0.4 q=-0.0 size=  229500kB time=00:00:03.54 bitrate=530841.6kbits/s speed=0.0163x
frame=   86 fps=0.4 q=-0.0 size=  232200kB time=00:00:03.58 bitrate=530841.6kbits/s speed=0.0162x
frame=   87 fps=0.4 q=-0.0 size=  234900kB time=00:00:03.62 bitrate=530841.6kbits/s speed=0.0161x
frame=   88 fps=0.4 q=-0.0 size=  237600kB time=00:00:03.66 bitrate=530841.6kbits/s speed=0.016x
frame=   89 fps=0.4 q=-0.0 size=  240300kB time=00:00:03.70 bitrate=530841.6kbits/s speed=0.0159x
frame=   90 fps=0.4 q=-0.0 size=  243000kB time=00:00:03.75 bitrate=530841.6kbits/s speed=0.0159x
frame=   91 fps=0.4 q=-0.0 size=  245700kB time=00:00:03.79 bitrate=530841.6kbits/s speed=0.0158x
frame=   92 fps=0.4 q=-0.0 size=  248400kB time=00:00:03.83 bitrate=530841.6kbits/s speed=0.0158x
frame=   93 fps=0.4 q=-0.0 size=  251100kB time=00:00:03.87 bitrate=530841.6kbits/s speed=0.0158x
frame=   94 fps=0.4 q=-0.0 size=  253800kB time=00:00:03.91 bitrate=530841.6kbits/s speed=0.0158x
frame=   95 fps=0.4 q=-0.0 size=  256500kB time=00:00:03.95 bitrate=530841.6kbits/s speed=0.0157x
frame=   96 fps=0.4 q=-0.0 size=  259200kB time=00:00:04.00 bitrate=530841.6kbits/s speed=0.0156x
frame=   96 fps=0.4 q=-0.0 size=  259200kB time=00:00:04.00 bitrate=530841.6kbits/s speed=0.0155x
frame=   96 fps=0.4 q=-0.0 Lsize=  259200kB time=00:00:04.00 bitrate=530841.6kbits/s speed=0.0155x
```

**Comment by rossluebe** [comment]
Try encoding your video without audio altogether. I was getting the same error until I completely removed the audio track from the encoding.
