### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by vishalkumar-prajapati** [samiare/whitewater-encoder#8]
When i type `whitewater --help` I get below error..

```
Traceback (most recent call last):
  File "C:\Users\Vishal\AppData\Local\Programs\Python\Python36-32\Scripts\whitewater-script.py", line 11, in <module>
    load_entry_point('whitewater==1.0.1', 'console_scripts', 'whitewater')()
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\whitewater\__init__.py", line 1, in <module>
    from .whitewater import Whitewater
  File "c:\users\vishal\appdata\local\programs\python\python36-32\lib\site-packages\whitewater\whitewater.py", line 641
    print message
                ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by vishalp36** [comment]
Solved  using python 2.713
